MiniP = {
    "M1_SET" : "MINI01",
    "M2_SET" : "MINI02",
    "RC1_SET" : "MINI03",
    "RC2_SET" : "MINI04",
    "RC3_SET" : "MINI05",
    "RC4_SET" : "MINI06",
    "D1_SET" : "MINI07",
    "D2_SET" : "MINI08",
    "D3_SET" : "MINI09",
    "D4_SET" : "MINI0A",
    "RGB1R_SET" : "MINI0B",
    "RGB1G_SET" : "MINI0C",
    "RGB1B_SET" : "MINI0D",
    "RGB2R_SET" : "MINI0E",
    "RGB2G_SET" : "MINI0F",
    "RGB2B_SET" : "MINI10",

    "BTN1_GET" : "MINI80",
    "BTN2_GET" : "MINI81",
    "D1_GET" : "MINI82",
    "D2_GET" : "MINI83",
    "D3_GET" : "MINI84",
    "D4_GET" : "MINI85",
    "A1_GET" : "MINI86",
    "A2_GET" : "MINI87",
    "A3_GET" : "MINI88"
    }
